### ISSUE TITLE
music FATAL Error

### ISSUE THREAD

**Issue by LeeHyKu** [LeeHyKu/Arknights-Chen-Discord#11]
← From target: {"method":"Runtime.consoleAPICalled","params":{"type":"error","args":[{"type":"string","value":"TypeError [ERR_INVALID_ARG_TYPE]: The \"url\" argument must be of type string. Received undefined\n    at validateString (internal/validators.js:120:11)\n    at Url.parse (url.js:159:3)\n    at Object.urlParse [as parse] (url.js:154:13)\n    at doDownload (C:\\Users\\harry\\source\\repos\\Chen\\Chen\\node_modules\\miniget\\dist\\index.js:90:28)\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)"}],"executionContextId":1,"timestamp":1588770278529.635,"stackTrace":{"callFrames":[{"functionName":"process.on.Screen._exceptionHandler","scriptId":"399","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/blessed/lib/widgets/screen.js","lineNumber":218,"columnNumber":12},{"functionName":"emit","scriptId":"14","url":"events.js","lineNumber":314,"columnNumber":19},{"functionName":"","scriptId":"40","url":"internal/process/execution.js","lineNumber":164,"columnNumber":24}],"parent":{"description":"TickObject","callFrames":[{"functionName":"init","scriptId":"48","url":"internal/inspector_async_hook.js","lineNumber":24,"columnNumber":18},{"functionName":"emitInitNative","scriptId":"23","url":"internal/async_hooks.js","lineNumber":143,"columnNumber":42},{"functionName":"emitInitScript","scriptId":"23","url":"internal/async_hooks.js","lineNumber":345,"columnNumber":2},{"functionName":"nextTick","scriptId":"24","url":"internal/process/task_queues.js","lineNumber":134,"columnNumber":4},{"functionName":"Miniget","scriptId":"550","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/miniget/dist/index.js","lineNumber":189,"columnNumber":12},{"functionName":"downloadFromInfoCallback","scriptId":"546","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/ytdl-core/lib/index.js","lineNumber":108,"columnNumber":10},{"functionName":"","scriptId":"546","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/ytdl-core/lib/index.js","lineNumber":22,"columnNumber":4},{"functionName":"","scriptId":"547","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/ytdl-core/lib/info.js","lineNumber":305,"columnNumber":22},{"functionName":"processTicksAndRejections","scriptId":"24","url":"internal/process/task_queues.js","lineNumber":96,"columnNumber":4}],"parent":{"description":"Promise.then","callFrames":[{"functionName":"exports.<computed>","scriptId":"547","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/ytdl-core/lib/info.js","lineNumber":305,"columnNumber":9},{"functionName":"ytdl","scriptId":"546","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/ytdl-core/lib/index.js","lineNumber":16,"columnNumber":7},{"functionName":"","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":285,"columnNumber":32},{"functionName":"","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":283,"columnNumber":19},{"functionName":"","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":7,"columnNumber":70},{"functionName":"__awaiter","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":3,"columnNumber":11},{"functionName":"fromYoutube","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":282,"columnNumber":15},{"functionName":"","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":127,"columnNumber":62},{"functionName":"","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":7,"columnNumber":70},{"functionName":"__awaiter","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":3,"columnNumber":11},{"functionName":"","scriptId":"545","url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js","lineNumber":123,"columnNumber":43},{"functionName":"emit","scriptId":"14","url":"events.js","lineNumber":326,"columnNumber":21},{"functionName":"finishMaybe","scriptId":"85","url":"_stream_writable.js","lineNumber":650,"columnNumber":13},{"functionName":"","scriptId":"85","url":"_stream_writable.js","lineNumber":626,"columnNumber":6},{"functionName":"_final","scriptId":"250","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js","lineNumber":247,"columnNumber":4},{"functionName":"callFinal","scriptId":"85","url":"_stream_writable.js","lineNumber":619,"columnNumber":9},{"functionName":"processTicksAndRejections","scriptId":"24","url":"internal/process/task_queues.js","lineNumber":83,"columnNumber":20}],"parent":{"description":"TickObject","callFrames":[{"functionName":"init","scriptId":"48","url":"internal/inspector_async_hook.js","lineNumber":24,"columnNumber":18},{"functionName":"emitInitNative","scriptId":"23","url":"internal/async_hooks.js","lineNumber":143,"columnNumber":42},{"functionName":"emitInitScript","scriptId":"23","url":"internal/async_hooks.js","lineNumber":345,"columnNumber":2},{"functionName":"nextTick","scriptId":"24","url":"internal/process/task_queues.js","lineNumber":134,"columnNumber":4},{"functionName":"prefinish","scriptId":"85","url":"_stream_writable.js","lineNumber":636,"columnNumber":14},{"functionName":"finishMaybe","scriptId":"85","url":"_stream_writable.js","lineNumber":647,"columnNumber":4},{"functionName":"afterWrite","scriptId":"85","url":"_stream_writable.js","lineNumber":479,"columnNumber":2},{"functionName":"onwrite","scriptId":"85","url":"_stream_writable.js","lineNumber":452,"columnNumber":6},{"functionName":"_writeCallback","scriptId":"250","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js","lineNumber":230,"columnNumber":6},{"functionName":"","scriptId":"250","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js","lineNumber":235,"columnNumber":78},{"functionName":"listOnTimeout","scriptId":"37","url":"internal/timers.js","lineNumber":548,"columnNumber":16},{"functionName":"processTimers","scriptId":"37","url":"internal/timers.js","lineNumber":491,"columnNumber":6}],"parent":{"description":"Timeout","callFrames":[{"functionName":"init","scriptId":"48","url":"internal/inspector_async_hook.js","lineNumber":24,"columnNumber":18},{"functionName":"emitInitNative","scriptId":"23","url":"internal/async_hooks.js","lineNumber":143,"columnNumber":42},{"functionName":"emitInitScript","scriptId":"23","url":"internal/async_hooks.js","lineNumber":345,"columnNumber":2},{"functionName":"initAsyncResource","scriptId":"37","url":"internal/timers.js","lineNumber":152,"columnNumber":4},{"functionName":"Timeout","scriptId":"37","url":"internal/timers.js","lineNumber":185,"columnNumber":2},{"functionName":"setTimeout","scriptId":"35","url":"timers.js","lineNumber":145,"columnNumber":18},{"functionName":"_step","scriptId":"250","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js","lineNumber":234,"columnNumber":6},{"functionName":"_write","scriptId":"250","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js","lineNumber":107,"columnNumber":9},{"functionName":"doWrite","scriptId":"85","url":"_stream_writable.js","lineNumber":391,"columnNumber":11},{"functionName":"writeOrBuffer","scriptId":"85","url":"_stream_writable.js","lineNumber":373,"columnNumber":4},{"functionName":"Writable.write","scriptId":"85","url":"_stream_writable.js","lineNumber":313,"columnNumber":11},{"functionName":"ondata","scriptId":"82","url":"_stream_readable.js","lineNumber":707,"columnNumber":21},{"functionName":"emit","scriptId":"14","url":"events.js","lineNumber":314,"columnNumber":19},{"functionName":"Readable.read","scriptId":"82","url":"_stream_readable.js","lineNumber":507,"columnNumber":9},{"functionName":"flow","scriptId":"82","url":"_stream_readable.js","lineNumber":978,"columnNumber":33},{"functionName":"pipeOnDrainFunctionResult","scriptId":"82","url":"_stream_readable.js","lineNumber":802,"columnNumber":6},{"functionName":"emit","scriptId":"14","url":"events.js","lineNumber":314,"columnNumber":19},{"functionName":"afterWrite","scriptId":"85","url":"_stream_writable.js","lineNumber":467,"columnNumber":11},{"functionName":"onwrite","scriptId":"85","url":"_stream_writable.js","lineNumber":452,"columnNumber":6},{"functionName":"_writeCallback","scriptId":"250","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js","lineNumber":230,"columnNumber":6},{"functionName":"","scriptId":"250","url":"file:///C:/Users/harry/source/repos/Chen/Chen/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js","lineNumber":235,"columnNumber":78},{"functionName":"listOnTimeout","scriptId":"37","url":"internal/timers.js","lineNumber":548,"columnNumber":16},{"functionName":"processTimers","scriptId":"37","url":"internal/timers.js","lineNumber":491,"columnNumber":6}],"parentId":{"id":"5"}}}}}}}}

**Comment by LeeHyKu** [comment]
{
"functionName":"",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":285,
"columnNumber":32
},
{
"functionName":"",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":283,
"columnNumber":19
},
{
"functionName":"",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":7,
"columnNumber":70
},
{
"functionName":"__awaiter",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":3,
"columnNumber":11
},
{
"functionName":"fromYoutube",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":282,
"columnNumber":15
},
{
"functionName":"",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":127,
"columnNumber":62
},
{
"functionName":"",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":7,
"columnNumber":70
},
{
"functionName":"__awaiter",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":3,
"columnNumber":11
},
{
"functionName":"",
"scriptId":"545",
"url":"file:///C:/Users/harry/source/repos/Chen/Chen/source/Music/Music.js",
"lineNumber":123,
"columnNumber":43
},

**Comment by LeeHyKu** [comment]
{"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"error","text":"TypeError [ERR_INVALID_ARG_TYPE]: The \"url\" argument must be of type string. Received undefined\n    at validateString (internal/validators.js:120:11)\n    at Url.parse (url.js:159:3)\n    at Object.urlParse [as parse] (url.js:154:13)\n    at doDownload (C:\\Users\\harry\\source\\repos\\Chen\\Chen\\node_modules\\miniget\\dist\\index.js:90:28)\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)","url":"C:\\Users\\harry\\source\\repos\\Chen\\Chen\\node_modules\\blessed\\lib\\widgets\\screen.js","line":219,"column":13}}}

**Comment by LeeHyKu** [comment]
issue when playing https://www.youtube.com/watch?v=6yjLlYNFKCg

**Comment by LeeHyKu** [comment]
node-ytdl-core problem
